---
- name: Add the OS specific varibles
  include_vars: "{{role_path}}/vars/{{ ansible_os_family }}.yml"

- name: Install the nrpe server packages
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items: "{{ nagios_nrpe_server_apt_packages }}"
  environment: "{{ env }}"
  when: ansible_os_family == "Debian"
  become: true
  tags: [packages,nrpe-server]

- name: Configure the nrpe server
  template: >
    src={{role_path}}/templates/nrpe.cfg.j2
    dest={{ nagios_nrpe_server_config_d_path }}/{{ nagios_nrpe_server_config_d_name }}
    mode=644
    backup=yes
  when: >
    nagios_nrpe_server_config|length > 0
    or nagios_nrpe_server_commands|length > 0
  become: true
  notify:
   - restart nagios-nrpe-server
  tags: [configuration,nrpe-server]

- name: Copy the plugins
  copy: >
    src={{ item }}
    dest={{ nagios_nrpe_server_plugins_path }}/
    mode=755
  with_fileglob:
    - "{{role_path}}/../files/nagios-plugins/*"
    - "{{role_path}}/../../files/nagios-plugins/*"
    - "{{role_path}}/../../../files/nagios-plugins/*"
  tags: [configuration,nrpe-server]

- name: Configure sudoers
  template: >
    src={{role_path}}/templates/sudoers.j2
    dest={{ nagios_nrpe_server_sudoers_d_path }}/{{ nagios_nrpe_server_sudoers_d_name }}
    mode=0640
    validate="visudo -cf %s"
  when: >
      nagios_nrpe_server_commands|length > 0
      or nagios_nrpe_server_sudo_commands|length > 0
  become: true
  tags: [configuration,nrpe-server]

- name: Start the nagios-nrpe-server service
  service: name={{ nagios_nrpe_server_service_name }} state=started enabled=yes
  tags: [service,nrpe-server]